default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password

development:
  <<: *default
  database: andrew_tech_development
  host: db

test:
  <<: *default
  database: andrew_tech_test
  host: db

production:
  <<: *default
  database: andrew_tech_production
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock

